name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        cd apps/backend
        npm install
        
    - name: Build
      run: |
        cd apps/backend
        npm run build
        
    - name: Run Tests
      run: |
        cd apps/backend
        npm test
      
    # Deploy step will be added once we have hosting setup
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Deploy to production 