name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/backend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Root Dependencies
      run: npm install
        
    - name: Install Backend Dependencies
      run: |
        cd apps/backend
        npm install
        
    - name: Lint
      run: |
        cd apps/backend
        npm run lint
        
    - name: Type Check
      run: |
        cd apps/backend
        npx tsc --noEmit
        
    - name: Run Tests
      run: |
        cd apps/backend
        npm run test
        
  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm install
        cd apps/backend
        npm install
        
    - name: Build
      run: |
        cd apps/backend
        npm run build

    - name: Install Railway CLI
      run: npm install @railway/cli

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: editai-backend
        root_dir: apps/backend