name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm install
        
    - name: Lint
      run: |
        cd apps/frontend
        npm run lint
        
    - name: Type Check
      run: |
        cd apps/frontend
        npx tsc --noEmit
        
    - name: Run Tests
      run: |
        cd apps/frontend
        npm run test
        
  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm install
        
    - name: Build
      run: |
        cd apps/frontend
        npm run build
        
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        npx vercel deploy --prod --token=$VERCEL_TOKEN 